const db = require('./connection');
const { Family, Resident } = require('../models');

db.once('open', async () => {
  await Family.deleteMany();
  await Resident.deleteMany();

  await Family.insertMany([
    {lastName:"Adams", alpha_id: 1},
    {lastName:"Allen", alpha_id: 2},
    {lastName:"America", alpha_id: 3},
    {lastName:"Anderson", alpha_id: 4},
    {lastName:"Asberry", alpha_id: 5},
    {lastName:"Aston", alpha_id: 6},
    {lastName:"Atwell", alpha_id: 7},
    {lastName:"Barr", alpha_id: 8},
    {lastName:"Berry", alpha_id: 9},
    {lastName:"Blackson", alpha_id: 10},
    {lastName:"Boggs", alpha_id: 11},
    {lastName:"Boyer", alpha_id: 12},
    {lastName:"Brown", alpha_id: 13},
    {lastName:"Burton", alpha_id: 14},
    {lastName:"Cardwell", alpha_id: 15},
    {lastName:"Carter", alpha_id: 16},
    {lastName:"Clark", alpha_id: 17},
    {lastName:"Cole", alpha_id: 18},
    {lastName:"Collier", alpha_id: 19},
    {lastName:"Collings", alpha_id: 20},
    {lastName:"Collman", alpha_id: 21},
    {lastName:"Dabney", alpha_id: 22},
    {lastName:"Davinger", alpha_id: 23},
    {lastName:"Davis", alpha_id: 24},
    {lastName:"Dorsey", alpha_id: 25},
    {lastName:"Douglas", alpha_id: 26},
    {lastName:"Drew", alpha_id: 27},
    {lastName:"Eliza", alpha_id: 28},
    {lastName:"Farley", alpha_id: 29},
    {lastName:"Ferguson", alpha_id: 30},
    {lastName:"Flowers", alpha_id: 31},
    {lastName:"Foreman", alpha_id: 32},
    {lastName:"Forman", alpha_id: 33},
    {lastName:"Fry", alpha_id: 34},
    {lastName:"Gibbs", alpha_id: 35},
    {lastName:"Grinnell", alpha_id: 36},
    {lastName:"Hammond", alpha_id: 37},
    {lastName:"Hanley", alpha_id: 38},
    {lastName:"Harris", alpha_id: 39},
    {lastName:"Henderson", alpha_id: 40},
    {lastName:"Henry", alpha_id: 41},
    {lastName:"Henson", alpha_id: 42},
    {lastName:"Hill", alpha_id: 43},
    {lastName:"Hilton", alpha_id: 44},
    {lastName:"Hines", alpha_id: 45},
    {lastName:"Jackson", alpha_id: 46},
    {lastName:"Jacobs", alpha_id: 47},
    {lastName:"James", alpha_id: 48},
    {lastName:"Jarrett", alpha_id: 49},
    {lastName:"Johns", alpha_id: 50},
    {lastName:"Johnson", alpha_id: 51},
    {lastName:"Jones", alpha_id: 52},
    {lastName:"Kelly-Nolan", alpha_id: 53},
    {lastName:"Kirk", alpha_id: 54},
    {lastName:"Leon", alpha_id: 55},
    {lastName:"Lewis", alpha_id: 56},
    {lastName:"Lordden", alpha_id: 57},
    {lastName:"Luckett", alpha_id: 58},
    {lastName:"Mapp", alpha_id: 59},
    {lastName:"Massey", alpha_id: 60},
    {lastName:"Matthewson", alpha_id: 61},
    {lastName:"McCulloms", alpha_id: 62},
    {lastName:"McLaughlin", alpha_id: 63},
    {lastName:"Miller", alpha_id: 64},
    {lastName:"Mills", alpha_id: 65},
    {lastName:"Mitchell", alpha_id: 66},
    {lastName:"Monroe", alpha_id: 67},
    {lastName:"Montagne", alpha_id: 68},
    {lastName:"Parker", alpha_id: 69},
    {lastName:"Picraft", alpha_id: 70},
    {lastName:"Pleasants", alpha_id: 71},
    {lastName:"Posey", alpha_id: 72},
    {lastName:"Price", alpha_id: 73},
    {lastName:"Pritchett", alpha_id: 74},
    {lastName:"Pycroft", alpha_id: 75},
    {lastName:"Raisen", alpha_id: 76},
    {lastName:"Ramey", alpha_id: 77},
    {lastName:"Reason", alpha_id: 78},
    {lastName:"Richfield", alpha_id: 79},
    {lastName:"Roberts", alpha_id: 80},
    {lastName:"Robinson", alpha_id: 81},
    {lastName:"Rudolph", alpha_id: 82},
    {lastName:"Scott", alpha_id: 83},
    {lastName:"Seyman", alpha_id: 84},
    {lastName:"Singleton", alpha_id: 85},
    {lastName:"Smith", alpha_id: 86},
    {lastName:"Sneed", alpha_id: 87},
    {lastName:"Stewart", alpha_id: 88},
    {lastName:"Styer", alpha_id: 89},
    {lastName:"Taylor", alpha_id: 90},
    {lastName:"Thomas", alpha_id: 91},
    {lastName:"Thompson", alpha_id: 92},
    {lastName:"Tinson", alpha_id: 93},
    {lastName:"Trowery", alpha_id: 94},
    {lastName:"Van Lear", alpha_id: 95},
    {lastName:"Vaughn", alpha_id: 96},
    {lastName:"Walker", alpha_id: 97},
    {lastName:"Warnick", alpha_id: 98},
    {lastName:"Washington", alpha_id: 99},
    {lastName:"Watson", alpha_id: 100},
    {lastName:"Whaley", alpha_id: 101},
    {lastName:"White", alpha_id: 102},
    {lastName:"Williams", alpha_id: 103},
    {lastName:"Wilmer", alpha_id: 104},
    {lastName:"Wilson", alpha_id: 105}
  
  ]);

  console.log('families seeded');
  process.exit();
})
